#!/usr/bin/env bash
#
# Deploy a trained wake word model into the BOX-3 firmware.
#
# Takes a .tflite file and:
#   1. Converts it to a C byte array header (hi_roo_model.h)
#   2. Copies the .tflite to the models/ directory
#   3. Optionally rebuilds the firmware
#
# Usage:
#   ./deploy.sh hi_roo.tflite              # convert + copy
#   ./deploy.sh hi_roo.tflite --rebuild    # convert + copy + rebuild firmware

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVICE_DIR="$(dirname "$SCRIPT_DIR")"
FIRMWARE_DIR="${DEVICE_DIR}/firmware"
MAIN_DIR="${FIRMWARE_DIR}/main"
MODELS_DIR="${FIRMWARE_DIR}/models"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <model.tflite> [--rebuild]"
    echo ""
    echo "Deploys a trained TFLite wake word model into the firmware."
    exit 1
fi

TFLITE_FILE="$1"
REBUILD=false
if [ "${2:-}" = "--rebuild" ]; then
    REBUILD=true
fi

if [ ! -f "$TFLITE_FILE" ]; then
    echo "ERROR: File not found: $TFLITE_FILE"
    exit 1
fi

SIZE=$(wc -c < "$TFLITE_FILE" | tr -d ' ')
SIZE_KB=$((SIZE / 1024))
echo "Model: $TFLITE_FILE ($SIZE_KB KB)"

if [ "$SIZE_KB" -gt 60 ]; then
    echo "WARNING: Model exceeds 60KB budget ($SIZE_KB KB). May not fit in tensor arena."
fi

# Step 1: Copy .tflite to models/
mkdir -p "$MODELS_DIR"
cp "$TFLITE_FILE" "${MODELS_DIR}/hi_roo.tflite"
echo "Copied to ${MODELS_DIR}/hi_roo.tflite"

# Step 2: Convert to C header using xxd
HEADER_FILE="${MAIN_DIR}/hi_roo_model.h"
echo "Generating C header..."

cat > "$HEADER_FILE" << 'HEADER_TOP'
/**
 * @file hi_roo_model.h
 * @brief Embedded TFLite wake word model for "Hi Roo".
 *
 * Auto-generated by deploy.sh from hi_roo.tflite.
 * Do not edit manually.
 */

#ifndef HI_ROO_MODEL_H
#define HI_ROO_MODEL_H

#include <stddef.h>

HEADER_TOP

# Generate the byte array
xxd -i "$TFLITE_FILE" | \
    sed 's/unsigned char .*/alignas(16) static const unsigned char hi_roo_model_data[] = {/' | \
    sed 's/unsigned int .*//' >> "$HEADER_FILE"

# Add size constant and close guard
cat >> "$HEADER_FILE" << HEADER_BOTTOM

static const size_t hi_roo_model_data_len = sizeof(hi_roo_model_data);

#endif /* HI_ROO_MODEL_H */
HEADER_BOTTOM

LINES=$(wc -l < "$HEADER_FILE" | tr -d ' ')
echo "Generated ${HEADER_FILE} (${LINES} lines)"

# Step 3: Rebuild firmware if requested
if [ "$REBUILD" = true ]; then
    echo ""
    echo "Rebuilding firmware..."
    cd "$DEVICE_DIR"
    ./build-firmware.sh
else
    echo ""
    echo "Model deployed. To rebuild firmware:"
    echo "  cd ${DEVICE_DIR} && ./build-firmware.sh"
fi
